# Generated by Django 3.1.1 on 2021-05-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_id', models.PositiveIntegerField(blank=True, null=True)),
                ('carrier_name', models.TextField(blank=True, null=True)),
                ('origin_id', models.PositiveIntegerField(blank=True, null=True)),
                ('origin_airport_name', models.TextField(blank=True, null=True)),
                ('origin_city_name', models.TextField(blank=True, null=True)),
                ('origin_skyscanner_code', models.CharField(blank=True, max_length=10, null=True)),
                ('destination_id', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_airport_name', models.TextField(blank=True, null=True)),
                ('destination_city_name', models.TextField(blank=True, null=True)),
                ('destination_skyscanner_code', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('minimum_price', models.PositiveIntegerField(blank=True, null=True)),
                ('is_flight_direct', models.BooleanField(default=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
