# Generated by Django 3.1.1 on 2021-05-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_flightsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities_info', models.JSONField(default=list)),
                ('trip_type', models.CharField(blank=True, choices=[('round_trip', 'round_trip'), ('one_way', 'one_way')], max_length=60, null=True)),
                ('trip_start_date', models.DateField(blank=True, null=True)),
                ('tripe_price', models.PositiveIntegerField(blank=True, null=True)),
                ('trip_return_day_interval', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
