# Generated by Django 3.1.1 on 2021-05-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_ordersdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersdata',
            old_name='tripe_price',
            new_name='trip_price',
        ),
    ]
