# Generated by Django 3.1.1 on 2021-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_auto_20210502_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersdata',
            name='cities_info',
        ),
        migrations.AddField(
            model_name='ordersdata',
            name='destination_city',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='ordersdata',
            name='origin_city',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
