# Generated by Django 3.1.1 on 2021-05-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_auto_20210502_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightsdata',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightsdata',
            name='trip_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
